name: Python Django Coverage GitHub Action
inputs:
  django-apps:
    description: "Application(s)"
    required: false
    default: ""
  minimum-coverage:
    description: "Minimum allowed code coverage"
    required: false
    default: "10"
  requirements-txt:
    description: "Path to the requirements.txt file"
    required: false
    default: "requirements.txt"
description: 'Github Action to run tests and get coverage with Django on a Python Docker image'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.django-apps }}
  - ${{ inputs.minimum-coverage }}
  - ${{ inputs.requirements-txt }}
